### ISSUE TITLE
(Recommendation) Linux Support

### ISSUE THREAD

**Issue by JPeisach** [GDColon/GD-Account-Manager#1]
So this script is only for Windows which I understand. I know for Linux it’s complicated but basically all this can be done using Perl or Bash.

And also: acc.js, if it is supposed to be ran using node ANYWHERE, should be added to path. For Linux you just need to put it in /bin.

I can open a merge request if you want to include these changes and I’ll translate your code under your copyright.

P.S I forgot to say-the REAL Difference is where the CC files are and the GD files are. It’s in the home directory for Linux, or ${HOME}

**Comment by suprstarrd** [comment]
I'll make a fork of this and see what I can do-- so the CCGameManager files are all in ${HOME}? Or is Steam in ${HOME}?

**Comment by JPeisach** [comment]
Try installing Gd on Linux. I am busy ATM but I will give you the path.

Yes it is in the .steam folder in ${HOME}
